# Generated by Django 4.2.7 on 2023-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='limit',
            field=models.IntegerField(default=2),
        ),
    ]
