# Generated by Django 4.2.7 on 2023-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_download_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='code',
            field=models.TextField(default='<django.db.models.fields.UUIDField>', max_length=50),
        ),
        migrations.AddField(
            model_name='download',
            name='link',
            field=models.TextField(default='https://tma.clickviral.tech/<django.db.models.fields.UUIDField>', max_length=50),
        ),
    ]
