# Generated by Django 4.2.7 on 2023-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_download_code_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='code',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='download',
            name='link',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
