# Generated by Django 4.2.7 on 2023-11-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_download_code_alter_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='code',
        ),
        migrations.RemoveField(
            model_name='download',
            name='link',
        ),
        migrations.AddField(
            model_name='download',
            name='name',
            field=models.CharField(default='unnamed_download', max_length=100),
        ),
    ]
