# Generated by Django 4.2.7 on 2023-11-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_download_code_remove_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
